import { BarterListing, CropCreditTrade, GlutAlert, CarbonPassport, DailyGradeData } from "./types";

export const MOCK_GLUT_ALERTS: GlutAlert[] = [
  {
    id: "glut-1",
    cropType: "Organic Tomatoes",
    zone: "North-4",
    surplusTons: 340,
    riskLevel: "critical",
    demandZone: "South-2",
    demandDeficitTons: 210,
    transitTime: "2 days",
    fuelCostOffset: 1850,
    projectedNetProfit: 12400,
    routeDistance: "420 km",
  },
  {
    id: "glut-2",
    cropType: "Alphonso Mangoes",
    zone: "West-2",
    surplusTons: 180,
    riskLevel: "high",
    demandZone: "East-1",
    demandDeficitTons: 140,
    transitTime: "3 days",
    fuelCostOffset: 2400,
    projectedNetProfit: 18700,
    routeDistance: "580 km",
  },
  {
    id: "glut-3",
    cropType: "Basmati Rice",
    zone: "North-1",
    surplusTons: 520,
    riskLevel: "critical",
    demandZone: "South-3",
    demandDeficitTons: 380,
    transitTime: "4 days",
    fuelCostOffset: 3100,
    projectedNetProfit: 28200,
    routeDistance: "720 km",
  },
  {
    id: "glut-4",
    cropType: "Red Potatoes",
    zone: "East-2",
    surplusTons: 95,
    riskLevel: "medium",
    demandZone: "West-1",
    demandDeficitTons: 75,
    transitTime: "1 day",
    fuelCostOffset: 920,
    projectedNetProfit: 5600,
    routeDistance: "190 km",
  },
];

export const MOCK_BARTER_LISTINGS: BarterListing[] = [
  {
    id: "barter-1",
    farmerName: "Rajesh Kumar",
    location: "Punjab, India",
    type: "equipment",
    title: "John Deere 5310 Tractor (45HP)",
    description: "Well-maintained tractor with rotavator attachment. Available for 3-5 day rentals. Diesel (50L/day) not included.",
    creditValue: 120,
    creditUnit: "kg wheat credits/day",
    available: true,
    rating: 4.8,
    tradesCompleted: 23,
  },
  {
    id: "barter-2",
    farmerName: "Lakshmi Devi",
    location: "Maharashtra, India",
    type: "compost",
    title: "Premium Vermicompost (2 tons)",
    description: "Organic vermicompost produced from cow dung and garden waste. Rich in NPK (2.5-1.5-1.8). Bagged and ready.",
    creditValue: 45,
    creditUnit: "kg rice credits/bag",
    available: true,
    rating: 4.9,
    tradesCompleted: 47,
  },
  {
    id: "barter-3",
    farmerName: "Amit Singh",
    location: "Uttar Pradesh, India",
    type: "equipment",
    title: "Super Seeder Machine (Happy Seeder)",
    description: "Zero-till happy seeder for wheat sowing. Includes operator training. Fuel covered by user.",
    creditValue: 200,
    creditUnit: "kg wheat credits/day",
    available: true,
    rating: 4.6,
    tradesCompleted: 15,
  },
  {
    id: "barter-4",
    farmerName: "Meena Sharma",
    location: "Gujarat, India",
    type: "labor",
    title: "Skilled Harvesting Team (5 workers)",
    description: "Experienced harvesting team available for 1-week engagements. Specialize in mango and cotton harvesting.",
    creditValue: 80,
    creditUnit: "kg crop credits/person/day",
    available: true,
    rating: 4.7,
    tradesCompleted: 31,
  },
  {
    id: "barter-5",
    farmerName: "Suresh Patel",
    location: "Rajasthan, India",
    type: "seeds",
    title: "High-Yield Mustard Seeds (Hybrid)",
    description: "DMH-11 hybrid mustard seeds. 25kg bags. Germination rate 95%+. Ideal for rabi season sowing.",
    creditValue: 35,
    creditUnit: "kg wheat credits/bag",
    available: false,
    rating: 4.5,
    tradesCompleted: 19,
  },
  {
    id: "barter-6",
    farmerName: "Priya Verma",
    location: "Karnataka, India",
    type: "equipment",
    title: "Solar-Powered Water Pump (5HP)",
    description: "DC solar submersible pump with 300W panels. Can irrigate 2 acres. Available on barter for compost or organic inputs.",
    creditValue: 90,
    creditUnit: "kg compost credits/day",
    available: true,
    rating: 4.9,
    tradesCompleted: 12,
  },
];

export const MOCK_CROP_TRADES: CropCreditTrade[] = [
  {
    id: "trade-1",
    fromFarmer: "Rajesh Kumar",
    toFarmer: "Amit Singh",
    offering: "John Deere Tractor (3 days)",
    requesting: "150 kg Wheat Credits",
    creditAmount: 150,
    status: "released",
    txHash: "0x8f3a…b9e2c1d4a5f6",
    timestamp: "2026-07-24T09:15:00Z",
    trustScore: 94,
  },
  {
    id: "trade-2",
    fromFarmer: "Lakshmi Devi",
    toFarmer: "Suresh Patel",
    offering: "5 bags Vermicompost",
    requesting: "180 kg Rice Credits",
    creditAmount: 180,
    status: "in-transit",
    txHash: "0x4d7b…c2a1e8f3b6d9",
    timestamp: "2026-07-26T14:30:00Z",
    trustScore: 87,
  },
  {
    id: "trade-3",
    fromFarmer: "Meena Sharma",
    toFarmer: "Priya Verma",
    offering: "Harvesting Team (3 workers, 5 days)",
    requesting: "300 kg Mixed Crop Credits",
    creditAmount: 300,
    status: "locked",
    txHash: "0x9c2e…f1d4a7b8e3c0",
    timestamp: "2026-07-27T11:00:00Z",
    trustScore: 82,
  },
  {
    id: "trade-4",
    fromFarmer: "Priya Verma",
    toFarmer: "Rajesh Kumar",
    offering: "Solar Pump (7 days)",
    requesting: "600 kg Compost Credits",
    creditAmount: 600,
    status: "locked",
    txHash: "0xb1a3…c8d2e5f9a4b7",
    timestamp: "2026-07-27T16:45:00Z",
    trustScore: 91,
  },
];

export const MOCK_CARBON_PASSPORT: CarbonPassport = {
  batchId: "AGP-CP-2026-07-28-1042",
  cropType: "Organic Tomatoes",
  farmer: "Lakshmi Devi",
  location: "Maharashtra, India",
  harvestDate: "2026-07-25",
  soilScore: 92,
  solarStoragePercent: 100,
  foodMilesSaved: 340,
  certifications: ["No-Till Verified", "Organic Certified", "Zero-Emission Chain", "Water-Smart"],
  co2Sequestered: 4.2,
  waterSaved: 12500,
  biodiversityScore: 88,
};

export const MOCK_GRADE_HISTORY: DailyGradeData[] = [
  { date: "2026-07-22", label: "Jul 22", avgScore: 87, avgPrice: 2.45, avgCarbonScore: 72, avgSoilScore: 68, submissions: 12, avgShelfLife: 14, topGrade: "A-" },
  { date: "2026-07-23", label: "Jul 23", avgScore: 91, avgPrice: 2.60, avgCarbonScore: 78, avgSoilScore: 74, submissions: 18, avgShelfLife: 16, topGrade: "A" },
  { date: "2026-07-24", label: "Jul 24", avgScore: 88, avgPrice: 2.55, avgCarbonScore: 75, avgSoilScore: 71, submissions: 15, avgShelfLife: 13, topGrade: "A-" },
  { date: "2026-07-25", label: "Jul 25", avgScore: 94, avgPrice: 2.85, avgCarbonScore: 82, avgSoilScore: 79, submissions: 22, avgShelfLife: 18, topGrade: "A" },
  { date: "2026-07-26", label: "Jul 26", avgScore: 90, avgPrice: 2.70, avgCarbonScore: 80, avgSoilScore: 76, submissions: 19, avgShelfLife: 15, topGrade: "A" },
  { date: "2026-07-27", label: "Jul 27", avgScore: 93, avgPrice: 2.90, avgCarbonScore: 84, avgSoilScore: 81, submissions: 25, avgShelfLife: 17, topGrade: "A+" },
  { date: "2026-07-28", label: "Today", avgScore: 96, avgPrice: 3.10, avgCarbonScore: 87, avgSoilScore: 85, submissions: 8, avgShelfLife: 19, topGrade: "A+" },
];
